/**
 * Exact JavaScript port of firmware/triage_model.h (auto-generated by
 * pipeline.py from a scikit-learn RandomForestClassifier, 7 trees,
 * max_depth <= 4, held-out accuracy 1.0000).
 *
 * Features: hr (bpm), spo2 (%), rr (breaths/min), hrv RMSSD (ms), co2 (ppm)
 * Classes: 0 = GREEN, 1 = YELLOW, 2 = RED
 * Tie-break favours the higher-severity class (fail-safe escalation), exactly
 * as kapha_triage_infer() does on the ESP32.
 */

export type TriageClass = 0 | 1 | 2;

export interface Vitals {
  hr: number;
  spo2: number;
  rr: number;
  hrv: number;
  co2: number;
}

/* eslint-disable @typescript-eslint/no-unused-vars */

function kapha_tree_0({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (rr <= 18.0) return 0;
  if (spo2 <= 89.950001) return 2;
  return 1;
}

function kapha_tree_1({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (spo2 <= 94.950001) {
    if (hrv <= 21.599999) return 2;
    if (co2 <= 1768.5) {
      if (rr <= 22.5) return 1;
      return 1;
    }
    return 1;
  }
  return 0;
}

function kapha_tree_2({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (hr <= 81.350002) return 0;
  if (spo2 <= 89.799999) return 2;
  return 1;
}

function kapha_tree_3({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (hr <= 81.400002) return 0;
  if (spo2 <= 90.100002) return 2;
  return 1;
}

function kapha_tree_4({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (rr <= 17.95) return 0;
  if (spo2 <= 90.0) return 2;
  return 1;
}

function kapha_tree_5({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (hr <= 81.350002) return 0;
  if (co2 <= 1986.0) {
    if (co2 <= 1704.0) return 1;
    return 1;
  }
  if (hrv <= 18.75) return 2;
  return 2;
}

function kapha_tree_6({ hr, spo2, rr, hrv, co2 }: Vitals): TriageClass {
  if (spo2 <= 89.950001) return 2;
  if (co2 <= 1009.0) return 0;
  return 1;
}

const FOREST = [
  kapha_tree_0,
  kapha_tree_1,
  kapha_tree_2,
  kapha_tree_3,
  kapha_tree_4,
  kapha_tree_5,
  kapha_tree_6,
];

export interface InferenceResult {
  label: TriageClass;
  votes: [number, number, number];
  perTree: TriageClass[];
  latencyMs: number;
  confidence: number;
}

/** Behavioural mirror of kapha_triage_infer(hr, spo2, rr, hrv, co2). */
export function kapha_triage_infer(v: Vitals): InferenceResult {
  const votes: [number, number, number] = [0, 0, 0];
  const perTree: TriageClass[] = [];
  for (const tree of FOREST) {
    const cls = tree(v);
    perTree.push(cls);
    votes[cls] += 1;
  }
  // >= : ties favour the higher-severity class
  let best: TriageClass = 0;
  let bestVotes = votes[0];
  for (const c of [1, 2] as TriageClass[]) {
    if (votes[c] >= bestVotes) {
      bestVotes = votes[c];
      best = c;
    }
  }
  // performance.now() is clamped coarsely in browsers, so time a 512-run
  // batch and report the true per-inference cost.
  const REPS = 512;
  const t0 = performance.now();
  for (let r = 0; r < REPS; r++) {
    for (const tree of FOREST) tree(v);
  }
  const latencyMs = (performance.now() - t0) / REPS;
  return { label: best, votes, perTree, latencyMs, confidence: bestVotes / FOREST.length };
}

export const TRIAGE_META: Record<
  TriageClass,
  { code: string; name: string; action: string; token: string }
> = {
  0: {
    code: "GREEN",
    name: "MINOR / AMBULATORY",
    action: "Monitor — no immediate intervention required",
    token: "var(--vital-green)",
  },
  1: {
    code: "YELLOW",
    name: "DELAYED",
    action: "Reassess in 10 min — escalate on deterioration",
    token: "var(--vital-amber)",
  },
  2: {
    code: "RED",
    name: "IMMEDIATE",
    action: "Evacuate now — airway / oxygenation compromise",
    token: "var(--vital-red)",
  },
};
